import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Share_Tech } from "next/font/google";
import Footer from "@/components/Footer";
import ArcReactor from "@/components/ArcReactor";
import SmallArcReactor from "@/components/SmallArcReactor";
import TransitionEffect from "@/hooks/TransitionEffect";

const techFont = Share_Tech({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-tech",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {

  
  return (
    <html >
      <body className={`${inter.className} ${techFont.variable} overflow-x-hidden flex flex-col min-h-screen`}>
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
        <div className="hidden md:flex">
          <SmallArcReactor />
        </div>
        <div className="md:hidden">
          <SmallArcReactor />
        </div>
        <Footer />
      </body>
    </html>
  );
  
}
